name: ecommerce
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.2.1
  fluttertoast: ^8.0.8

  # Local Database
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3

  # Image and Permissions
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  flutter_animate: ^4.1.1  # Use the latest version from pub.dev

  # State Management
  provider: ^6.1.2
  intl: ^0.18.1

  # Optionnels pour plus tard :
  # flutter_riverpod: ^2.5.1
  # image_picker: ^1.1.1
  # firebase_storage: ^11.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
